---
- block:
    - name: Obtain JDK
      unarchive: >
        src="{{ jdk8_download_url }}" remote_src=true
        dest="{{ jdk8_home | dirname }}"
        creates="{{ jdk8_home }}/bin/java"
        validate_certs=no

    - name: JDK profile
      copy:
        dest: "{{ jdk8_profile }}"
        content: |
          export JAVA_HOME="{{ jdk8_home }}"
          export JRE_HOME="${JAVA_HOME}/jre"
          export DERBY_HOME="${JAVA_HOME}/db"
          export PATH="$PATH:$JAVA_HOME/bin:${DERBY_HOME}/bin:${JRE_HOME}/bin"
          export J2SDKDIR="${JAVA_HOME}"
          export J2REDIR="${JRE_HOME}"

  become: Yes
  when: ansible_os_family == "Debian"

