- block:
    - name: Ensure mysql server
      apt: name="mysql-server" update_cache=Yes cache_valid_time=259200
      tags:
        - install-mysql-server

    - name: Ensure python mysql module
      apt: name="python-mysqldb" update_cache=Yes cache_valid_time=259200

    - name: Ensure mysql service
      service: name=mysql state=started enabled=yes

  become: Yes
  when: ansible_os_family == "Debian"

- name: Ensure mysql database
  mysql_db: name="{{ mysql.database }}" state=present
  become: Yes

- name: MySQL user
  mysql_user: user="{{ mysql.user }}" password="{{ mysql.password }}" host="{{ item }}" priv="{{ mysql.database }}.*:ALL,GRANT" state=present
  with_items:
    - localhost
    - "%"
  become: Yes
